input LoginInput {
  username: String!
  password: String!
}

type UserLogin {
  user: User!
  canManageTenant: Boolean!
  onboardingTeams: [Team!]!
}

type Query {
  me: UserLogin!
}

type Mutation {
  login(dto: LoginInput!): UserLogin!
  logout: Boolean!
}
