type Me {
  canManageTenant: Boolean!
  user: User!
}

type Query {
  me: Me!
}

input LoginInput {
  username: String!
  password: String!
}

type Mutation {
  login(dto: LoginInput!): String!
  logout: Boolean!
}
