export enum EntityName {
  Actor = 'Actor',
  ActorImage = 'ActorImage',
  ActorTag = 'ActorTag',
  Address = 'Address',
  BankInfo = 'BankInfo',
  LegalUnit = 'LegalUnit',
  LegalUnitLocation = 'LegalUnitLocation',
  Social = 'Social',
  Transaction = 'Transaction',

  Event = 'Event',
  EventFavorite = 'EventFavorite',
  EventJoin = 'EventJoin',
  EventOrganize = 'EventOrganize',
  EventSupervisor = 'EventSupervisor',

  Tenant = 'Tenant',
  Campus = 'Campus',
  CampusCluster = 'CampusCluster',
  EventApproval = 'EventApproval',
  EventApprovalStep = 'EventApprovalStep',
  EventApprovalValidator = 'EventApprovalValidator',
  TenantMember = 'TenantMember',
  TenantMemberRole = 'TenantMemberRole',
  TenantRole = 'TenantRole',

  Team = 'Team',
  Action = 'Action',
  BankAccount = 'BankAccount',
  Expense = 'Expense',
  ExpenseItem = 'ExpenseItem',
  Grant = 'Grant',
  GrantAllocate = 'GrantAllocate',
  Mission = 'Mission',
  MissionJoin = 'MissionJoin',
  Project = 'Project',
  TeamDocument = 'TeamDocument',
  TeamHistory = 'TeamHistory',
  TeamJoin = 'TeamJoin',
  TeamMember = 'TeamMember',
  TeamMemberRole = 'TeamMemberRole',
  TeamRole = 'TeamRole',

  Form = 'Form',
  FormSubmission = 'FormSubmission',

  User = 'User',
  Follow = 'Follow',
  Session = 'Session',

  FileUpload = 'FileUpload',
  Location = 'Location',
  Tag = 'Tag',
}

// TODO: add test to match all *.entity.ts files with this list (all entities except Log)
