- name: 'type: question'
  description: Issues that asks a question.
  color: 'D4C5F9'
- name: 'type: feature'
  description: Issues/PRs that requests/adds a new feature.
  color: '0052CC'
- name: 'type: enhancement'
  description: Issues/PRs that requests/adds an improvement to an existing feature.
  color: '5319E7'
- name: 'type: bug'
  description: Issues/PRs that reports or fixes a bug.
  color: 'D93F0B'
- name: 'type: dependencies'
  description: Issues/PRs that updates dependencies.
  color: '699DE5'

- name: 'status: blocked'
  description: PRs that are blocked by other issues/PRs.
  color: 'E85247'
- name: 'status: needs testing'
  description: PRs that need testing from the author or volunteers.
  color: 'A55124'
- name: 'status: help wanted'
  description: Issues that need assistance from volunteers or PRs that need help to proceed.
  color: '008672'
- name: 'status: unconfirmed'
  description: Issues and PRs that are not approved yet.
  color: 'DB6A3D'
- name: 'status: approved'
  description: Issues and PRs that have been approved.
  color: '8CE098'

- name: 'priority: critical'
  description: Issues that must be fixed or PRs that must be finished and merged with MAXIMUM PRIORITY.
  color: 'F45B0E'
- name: 'priority: high'
  description: Issues that must be fixed or PRs that must be finished and merged with high priority.
  color: 'F48750'
- name: 'priority: medium'
  description: Issues that must be fixed or PRs that must be finished and merged with medium priority.
  color: 'FBCA04'
- name: 'priority: low'
  description: Issues that must be fixed or PRs that must be finished and merged with low priority.
  color: '9CEB34'
- name: 'priority: lowest'
  description: Issues that must be fixed or PRs that must be finished with the looowwwest priority.
  color: '41FC02'

- name: 'target: backend'
  description: Issues and PRs that act on the backend.
  color: 'C2E0C6'
- name: 'target: frontend'
  description: Issues and PRs that act on the frontend.
  color: 'C2E0C6'

- name: 'scope: *'
  description: Issues and PRs related to the whole site.
  color: '9DCBE0'
- name: 'scope: forum'
  description: Issues and PRs related to the forum module.
  color: '9DCBE0'
- name: 'scope: blog'
  description: Issues and PRs related to the blog module.
  color: '9DCBE0'
- name: 'scope: admin'
  description: Issues and PRs related to the admin module.
  color: '9DCBE0'
- name: 'scope: file sharing'
  description: Issues and PRs related to the file sharing module.
  color: '9DCBE0'
- name: 'scope: user'
  description: Issues and PRs related to users and profiles.
  color: '9DCBE0'
- name: 'scope: auth'
  description: Issues and PRs related to authentication.
  color: '9DCBE0'
- name: 'scope: wiki'
  description: Issues and PRs related to the wiki module.
  color: '9DCBE0'
- name: 'scope: restaurant (crous)'
  description: Issues and PRs related to restaurant module (the CROUS).
  color: '9DCBE0'
- name: 'scope: teams'
  description: Issues and PRs related to the teams module.
  color: '9DCBE0'
