version: '3'
name: okampus

services:
  postgres:
    image: postgres:15.2-alpine
    env_file:
      - ./apps/site/.env
      - ./apps/site/.env.development
    ports:
      - ${POSTGRES_PUBLISHED_PORT}:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./apps/site/database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./apps/site/.env
      - ./apps/site/.env.development
    ports:
      - ${PGADMIN_PUBLISHED_PORT}:80

  redis:
    image: redis/redis-stack:latest
    env_file:
      - ./apps/site/.env
      - ./apps/site/.env.development
    ports:
      - ${REDIS_PUBLISHED_PORT}:6379
      - ${REDISINSIGHT_PUBLISHED_PORT}:8001
    volumes:
      - ./.data/redis:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes

  minio:
    image: minio/minio
    env_file:
      - ./apps/site/.env
      - ./apps/site/.env.development
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
    command: server --console-address ":9001" /data
    ports:
      - 19000:9000
      - 19001:9001
    volumes:
      - ./.data/minio:/data

  meilisearch:
    image: getmeili/meilisearch
    env_file:
      - ./apps/site/.env
      - ./apps/site/.env.development
    ports:
      - ${MEILI_PUBLISHED_PORT}:7700
    volumes:
      - ./.data/meili:/meili_data
