version: '3'
name: okampus

services:
  postgres:
    image: postgres:15.2-alpine
    env_file: ./apps/site/.env.development
    ports:
      - ${POSTGRES_PUBLISHED_PORT}:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./apps/site/database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./apps/site/.env.development
    ports:
      - ${PGADMIN_PUBLISHED_PORT}:80

  hasura:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    env_file: ./apps/site/.env.development
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: false
      HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: true
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"${JWT_ALGORITHM}\",\"key\":\"${ACCESS_TOKEN_SECRET}\",\"header\":{\"type\":\"Cookie\",\"name\":\"OKAMPUS_ACCESS_TOKEN\"}}"
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${PSQL_USER}:${PSQL_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./apps/site/database/hasura/metadata:/hasura-metadata

  redis:
    image: redis/redis-stack:latest
    env_file: ./apps/site/.env.development
    ports:
      - ${REDIS_PUBLISHED_PORT}:6379
      - ${REDISINSIGHT_PUBLISHED_PORT}:8001
    volumes:
      - ./.data/redis:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes

  minio:
    image: minio/minio
    env_file: ./apps/site/.env.development
    command: server --console-address ":9001" /data
    ports:
      - 19000:9000
      - 19001:9001
    volumes:
      - ./.data/minio:/data

  meilisearch:
    image: getmeili/meilisearch
    env_file: ./apps/site/.env.development
    ports:
      - ${MEILI_PUBLISHED_PORT}:7700
    volumes:
      - ./.data/meili:/meili_data
