version: '3.9'

services:
  database:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
      PORT: 5051

  typesense:
    image: typesense/typesense:0.23.0
    restart: always
    volumes:
      - ./data/typesense:/tmp/typesense-data
    environment:
      TYPESENSE_DATA_DIR: ${TYPESENSE_DATA_DIR}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_ENABLE_CORS: "true"

  api:
    build: ./apps/api
    restart: always
    depends_on:
      - redis
      - database
      - typesense
    volumes:
      - ./apps/api/uploads:/app/uploads
    environment:
      WAIT_HOSTS: database:5432, redis:6379, typesense:8108
      MIKRO_ORM_HOST: ${MIKRO_ORM_HOST}
      TYPESENSE_HOST: ${TYPESENSE_HOST}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
