export enum SubscriptionType {
  ContentAdded = 'contentAdded',
  ContentUpdated = 'contentUpdated',
  FavoriteUpdated = 'favoriteUpdated',
  ReportAdded = 'reportAdded',
  TeamAdded = 'teamAdded',
  TeamUpdated = 'teamUpdated',
  TeamFinanceAdded = 'teamFinanceAdded',
  TeamFinanceUpdated = 'teamFinanceUpdated',
  TeamEventRegistrationAdded = 'teamEventRegistrationAdded',
  TeamEventRegistrationUpdated = 'teamEventRegistrationUpdated',
  TeamMemberInvited = 'teamMemberInvited',
  TeamMemberUpdated = 'teamMemberUpdated',
  TeamMemberRemoved = 'teamMemberRemoved',
  TeamMembershipRequestAdded = 'teamMembershipRequestAdded',
  TeamMembershipRequestUpdated = 'teamMembershipRequestUpdated',
  ThreadAdded = 'threadAdded',
  ThreadUpdated = 'threadUpdated',
  UserUpdated = 'userUpdated',
  VoteUpdated = 'voteUpdated',
}
