export enum SubscriptionType {
  ContentAdded = 'contentAdded',
  ContentUpdated = 'contentUpdated',
  FavoriteUpdated = 'favoriteUpdated',
  ReportAdded = 'reportAdded',
  TeamAdded = 'teamAdded',
  TeamUpdated = 'teamUpdated',
  TeamFinanceAdded = 'teamFinanceAdded',
  TeamFinanceUpdated = 'teamFinanceUpdated',
  TeamEventRegistrationAdded = 'teamEventRegistrationAdded',
  TeamEventRegistrationUpdated = 'teamEventRegistrationUpdated',
  ThreadAdded = 'threadAdded',
  ThreadUpdated = 'threadUpdated',
  VoteUpdated = 'voteUpdated',
}
