export enum SubscriptionType {
  ContentAdded = 'ContentAdded',
  ContentUpdated = 'ContentUpdated',
  FavoriteUpdated = 'FavoriteUpdated',
  ReportAdded = 'ReportAdded',
  TeamAdded = 'TeamAdded',
  TeamUpdated = 'TeamUpdated',
  TeamFinanceAdded = 'TeamFinanceAdded',
  TeamFinanceUpdated = 'TeamFinanceUpdated',
  EventRegistrationAdded = 'EventRegistrationAdded',
  EventRegistrationUpdated = 'EventRegistrationUpdated',
  TeamMemberInvited = 'TeamMemberInvited',
  TeamMemberUpdated = 'TeamMemberUpdated',
  TeamMemberRemoved = 'TeamMemberRemoved',
  TeamMembershipRequestAdded = 'TeamMembershipRequestAdded',
  TeamMembershipRequestUpdated = 'TeamMembershipRequestUpdated',
  ThreadAdded = 'ThreadAdded',
  ThreadUpdated = 'ThreadUpdated',
  UserUpdated = 'UserUpdated',
  VoteUpdated = 'VoteUpdated',
}
