  # measured in seconds
  ttl: Int! = 60

  # refresh the cache entry
  refresh: Boolean! = false
) on QUERY

type Query {
  # There are no queries available to the current role. Either there are no
  # sources or remote schemas configured, or the current role doesn't have the
  # required permissions.
  no_queries_available: String!
}

