type LineItem {
  name: String!
  quantity: Int!
  price: Float!
}

type ProcessedReceipt {
  amount: Float
  lineItems: [LineItem!]!
  address: String!
  tax: Float
  date: String
  vendorName: String
  phone: String
}

type Query {
  processReceipt(key: String!): ProcessedReceipt
}
