export enum SocialType {
  Mail = 'Mail',
  Site = 'Site',
  Discord = 'Discord',
  GitHub = 'GitHub',
  TikTok = 'TikTok',
  LinkedIn = 'LinkedIn',
  Instagram = 'Instagram',
  Facebook = 'Facebook',
  YouTube = 'YouTube',
  Twitch = 'Twitch',
  // BeReal = 'BeReal',
  // Signal = 'Signal',
  // WhatsApp = 'WhatsApp',
  // Telegram = 'Telegram',
}
