name: Build backend

on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'apps/api/**'
      - 'libs/api/**'
      - '!*/**/*.md'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: rg.fr-par.scw.cloud/okampus

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./apps/api/Dockerfile
          tags: |
            rg.fr-par.scw.cloud/okampus/okampus:${{ github.sha }}
            rg.fr-par.scw.cloud/okampus/okampus:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
