name: Deploy preproduction

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/api/**'
      - '!*/**/*.md'
      - '.github/workflows/backend-deploy-prod.yml'

jobs:
  bump:
    name: Edit infra chart parameters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: 'Okampus/infra'
        
    - name: Set version and save file
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.okampus.image.tag = "${{ github.sha }}"' 'values-preprod.yaml'

    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Updated preprod deployment to ${{ github.sha }}
          
          https://github.com/Okampus/okampus/tree/${{ github.sha }}'
          git push
    