name: Automatic Label Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
    paths:
      - '.github/labels.yml'

jobs:
  label_sync:
    name: Automatic Label Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Run Label Sync
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.OKAMPUS_AUTOMATIONS }}
          yaml-file: .github/labels.yml
